/* Version 1 */

CREATE DATABASE IF NOT EXISTS library;
USE library;

CREATE TABLE IF NOT EXISTS books(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
  	name VARCHAR(160) NOT NULL,
    description TEXT
);